name: Publish IBPS Packages
run-name: Publish_IBPS_Packages-${{ github.event.inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'version'
        required: true
        
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code from Dispatched Repo
      uses: actions/checkout@v4
      
    - name: Grant execute permission
      run: chmod +x release.zip
      
    - name: Upload ZIP to artifact
      uses: actions/upload-artifact@v2
      with:
          name: release.zip
          path: release.zip  
          
    - name: Publish package
      env:
         GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB}}
      run: |
         curl -X PUT -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/zip" --data-binary @release.zip "https://maven.pkg.github.com/rakbank-internal/ibps-was-ansible-cd/Rak/IBPS/release/${{ github.event.inputs.version }}/release-${{ github.event.inputs.version }}.zip"
